# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f0ae2df19c6102c3a5a8dbf32a1e1f4f8efa13ef0f770ac9ec99300597785e3a3c430c5c6edc61c08f0c0ade0f6191f80b2872af72298ebc95e2c8464f86e14

test:
  secret_key_base: 4de8bf18500e3e068b6efe792b89285e49079733a9b22b8e6cb2175b4bfe4dd5ae4350a47a2167aef33c8fec76181cd2ffd628aa19fffbd2a3bb7bed8ff0bd21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
